<?php /*a:3:{s:44:"E:\Pro\pro\ZP\app\news\view\index\index.html";i:1595475123;s:37:"E:\Pro\pro\ZP\app\news\view\main.html";i:1595475123;s:51:"E:\Pro\pro\ZP\app\news\view\index\index_search.html";i:1595475123;}*/ ?>
<div class="layui-card layui-bg-gray"><?php if(!(empty($title) || (($title instanceof \think\Collection || $title instanceof \think\Paginator ) && $title->isEmpty()))): ?><div class="layui-card-header notselect"><span class="layui-icon layui-icon-next font-s10 color-desc margin-right-5"></span><?php echo htmlentities((isset($title) && ($title !== '')?$title:'')); ?><div class="pull-right"><?php if(auth("add")): ?><button data-modal='<?php echo url("add"); ?>' data-title="添加政策" class='layui-btn layui-btn-sm layui-btn-primary'>添加政策</button><?php endif; ?></div></div><?php endif; ?><div class="layui-card-body"><div class="layui-tab layui-tab-card think-bg-white"><div class="layui-tab-content think-box-shadow"><fieldset><legend>条件搜索</legend><form class="layui-form layui-form-pane form-search" action="<?php echo request()->url(); ?>" onsubmit="return false" method="get" autocomplete="off"><div class="layui-form-item layui-inline"><label class="layui-form-label">类型</label><div class="layui-input-inline"><select id="news_type_Element" name="news_type_id" class="layui-select"><option value="all">全部</option></select></div></div><div class="layui-form-item layui-inline"><label class="layui-form-label">起始日期</label><div class="layui-input-inline"><input name="start_date" type="date" value="<?php echo input('start_date'); ?>" class="layui-input"></div></div><div class="layui-form-item layui-inline"><label class="layui-form-label">截止日期</label><div class="layui-input-inline"><input name="end_date" type="date" value="<?php echo input('end_date'); ?>" class="layui-input"></div></div><div class="layui-form-item layui-inline"><button class="layui-btn layui-btn-primary"><i class="layui-icon">&#xe615;</i> 搜 索</button></div></form></fieldset><script>    $.ajax({
        url:"<?php echo url('news/type/typeArray'); ?>",
        success:function(data){
            data = JSON.parse(data);
            var news_type_id = "<?php echo input('news_type_id'); ?>";
            var select = "";
            for(var i = 0;i < data.length;i++){
                select = "";
                if(news_type_id != "all" && news_type_id == data[i].news_type_id){
                    select = "selected";
                }
                $("#news_type_Element").append("<option " + select + " value='" + data[i].news_type_id + "'>" + data[i].spl + data[i].type_name + "</option>");
            }
            form.render();
        }
    });
    form.render();
</script><table class="layui-table margin-top-10" lay-skin="line"><?php if(!(empty($list) || (($list instanceof \think\Collection || $list instanceof \think\Paginator ) && $list->isEmpty()))): ?><thead><tr><th class='list-table-sort-td'><button type="button" data-reload class="layui-btn layui-btn-xs">刷 新</button></th><th class='text-left nowrap'>标题</th><th class='text-left nowrap'>分类</th><th class='text-left nowrap'>创建日期</th><th class='text-left nowrap'>操作</th></tr></thead><?php endif; ?><tbody><?php foreach($list as $key=>$vo): ?><tr data-dbclick><td></td><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo (isset($vo['title']) && ($vo['title'] !== '')?$vo['title']:''); ?></span></div></td><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo (isset($vo['type_name']) && ($vo['type_name'] !== '')?$vo['type_name']:''); ?></span></div></td><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo (isset($vo['create_time_text']) && ($vo['create_time_text'] !== '')?$vo['create_time_text']:''); ?></span></div></td><td class='text-left nowrap'><a class="layui-btn layui-btn-xs" data-title="网页预览" href='<?php echo url("info"); ?>?news_id=<?php echo htmlentities($vo['news_id']); ?>' target="_blank">网页预览</a><?php if(auth("edit")): ?><a data-dbclick class="layui-btn layui-btn-xs" data-title="编辑" data-modal='<?php echo url("edit"); ?>?news_id=<?php echo htmlentities($vo['news_id']); ?>'>编 辑</a><?php endif; if(auth("remove")): ?><a class="layui-btn layui-btn-danger layui-btn-xs" data-confirm="确定要删除吗?" data-action="<?php echo url('remove'); ?>" data-value="news_id#<?php echo htmlentities($vo['news_id']); ?>" data-csrf="<?php echo systoken('remove'); ?>">删 除</a><?php endif; ?></td></tr><?php endforeach; ?></tbody></table><?php if(empty($list) || (($list instanceof \think\Collection || $list instanceof \think\Paginator ) && $list->isEmpty())): ?><span class="notdata">没有记录哦</span><?php else: ?><?php echo (isset($pagehtml) && ($pagehtml !== '')?$pagehtml:''); ?><?php endif; ?></div></div></div></div>