<?php /*a:3:{s:46:"E:\Pro\pro\ZP\app\orders\view\index\index.html";i:1597382359;s:53:"E:\Pro\pro\ZP\app\orders\view\index\index_search.html";i:1595475123;s:47:"E:\Pro\pro\ZP\app\orders\view\index\orders.html";i:1597460482;}*/ ?>
<div><button data-modal='<?php echo url("add2"); ?>' data-title="预下单" class='layui-btn layui-btn-normal layui-btn-primary'>预下单</button></div><div class="layui-tab layui-tab-card think-bg-white"><div class="layui-tab-content think-box-shadow"><fieldset><legend>条件搜索</legend><form class="layui-form layui-form-pane form-search" action="<?php echo request()->url(); ?>" onsubmit="return false" method="get" autocomplete="off"><div class="layui-form-item layui-inline"><label class="layui-form-label">订单编号</label><div class="layui-input-inline"><input id="orders_id_value" name="orders_id" value="<?php echo input('orders_id'); ?>" placeholder="请输入订单编号" class="layui-input"></div></div><div class="layui-form-item layui-inline"><label class="layui-form-label">技术咨询师</label><div class="layui-input-inline"><input name="responsible_username" value="<?php echo input('responsible_username'); ?>" placeholder="请输入用户名或名称" class="layui-input"></div></div><div class="layui-form-item layui-inline"><label class="layui-form-label">企业名称</label><div class="layui-input-inline"><input name="enterprise_name" value="<?php echo input('enterprise_name'); ?>" placeholder="请输入企业名称" class="layui-input"></div></div><div class="layui-form-item layui-inline"><label class="layui-form-label">项目名称</label><div class="layui-input-inline"><input name="project_name" value="<?php echo input('project_name'); ?>" placeholder="请输入项目名称" class="layui-input"></div></div><div class="layui-form-item layui-inline"><label class="layui-form-label">部门</label><div class="layui-input-inline"><select id="department_search" name="department" class="layui-select"><option value="all">全部</option><option value="PROJECT">项目部</option><option value="DICHOTOMY">两化部</option><option value="KNOWLEDGE">知识产权部</option><option value="FINANCE">财务部</option></select></div></div><div class="layui-form-item layui-inline"><label class="layui-form-label">开始日期</label><div class="layui-input-inline"><input id="start_date_value" type="date" name="start_date" value="<?php echo input('start_date'); ?>" class="layui-input"></div></div><div class="layui-form-item layui-inline"><label class="layui-form-label">结束日期</label><div class="layui-input-inline"><input id="end_date_value" type="date" name="end_date" value="<?php echo input('end_date'); ?>" class="layui-input"></div></div><div class="layui-form-item layui-inline"><button class="layui-btn layui-btn-primary"><i class="layui-icon">&#xe615;</i> 搜 索</button><button class="layui-btn layui-btn-primary" type="button" onclick="exportExcel()"><i class="layui-icon layui-icon-export"></i>导 出</button></div></form></fieldset><script>    var department_value = "<?php echo input('department'); ?>";
    if(department_value != "" && department_value != "all"){
        var department_element = document.getElementById("department_search");
        for(var i = 0;i < department_element.length;i++){
            if(department_value == department_element[i].value){
                department_element[i].selected = true;
                break;
            }
        }
    }

    function exportExcel(){
        var url = "<?php echo url('exportExcel'); ?>?orders_id=" + $("#orders_id_value").val() + "&project_id=" + $("#project").val() + "&start_date=" + $("#start_date_value").val() + "&end_date=" + $("#end_date_value").val();
        var a = document.createElement("a");
        a.setAttribute("href",url);
        a.click();
    }

    form.render();
</script><div class="layui-tab layui-tab-brief"><ul class="layui-tab-title"><li class="layui-this" id="WaitToApprovalOrders">待审核订单</li><li id="DepartmentOrders">本部门订单</li><li id="FinishedOrders">完成订单</li><li id="RejectOrders">驳回订单</li><li id="AllOrders">全部订单</li></ul><div id="orders"><!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"></head><body><table class="layui-table margin-top-0" lay-skin="line"><?php if(!(empty($list) || (($list instanceof \think\Collection || $list instanceof \think\Paginator ) && $list->isEmpty()))): ?><thead><tr id="th1"><th class='list-table-sort-td'><button type="button" data-reload class="layui-btn layui-btn-xs">刷 新</button></th><th class='text-left nowrap'>订单号</th><th class='text-left nowrap'>项目名称</th><th class='text-left nowrap'>企业名称</th><th class='text-left nowrap'>部门</th><th class='text-left nowrap'>接单人员</th><th class='text-left nowrap'>技术咨询师</th><th class='text-left nowrap'>状态</th><th class='text-left nowrap'>下单日期</th><th class='text-left nowrap'>操作</th><th class='text-left nowrap'>审核记录</th></tr></thead><tbody><?php foreach($list as $key=>$vo): ?><tr><td></td><!-- 订单号 --><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo (isset($vo['orders_id']) && ($vo['orders_id'] !== '')?$vo['orders_id']:''); ?></span></div></td><!-- 项目名称 --><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo ($vo->getProjectName($vo->project_id) ?: ''); ?></span></div></td><!-- 企业名称 --><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo ($vo->getEnterpriseName($vo->enterprise_id) ?: ''); ?></span></div></td><!-- 部门 --><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo (isset($vo->department) && ($vo->department !== '')?$vo->department:''); ?></span></div></td><!-- 接单人 --><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo getNicknames($vo->receiving_user_ids) ?></span></div></td><!-- 技术咨询师 --><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo getNickname($vo->stage_reviewer) ?></span></div></td><!-- 状态 --><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php if($vo['state'] == 'REJECT'): ?>                    驳回
                <?php elseif($vo['state'] == 'FINISH'): ?>                    完成审核
                <?php else: ?><?php echo htmlentities((isset($vo['stage']) && ($vo['stage'] !== '')?$vo['stage']:'')); ?><?php endif; ?></span></div></td><!-- 创建日期 --><td class='text-left nowrap'><div class="inline-block sub-span-blue"><span><?php echo (isset($vo['create_time']) && ($vo['create_time'] !== '')?$vo['create_time']:''); ?></span></div></td><!-- 操作 --><td class='text-left nowrap'><a class="layui-btn layui-btn-xs" data-modal='<?php echo url("processReview/process"); ?>?orders_id=<?php echo htmlentities($vo['orders_id']); ?>'><?php if($vo['stage_reviewer'] == $myId): ?>        审核
        <?php else: ?>        查看
        <?php endif; ?></a><a data-dbclick class="layui-btn layui-btn-xs layui-btn-checked" data-title="编辑" data-modal=<?php echo url("index/edit2",["order_id"=>$vo['orders_id']]); ?>>编 辑</a><?php if($myOrderAuth == 8): ?><a class="layui-btn layui-btn-danger layui-btn-xs" data-confirm="确定要删除吗?" data-action="<?php echo url('index/remove'); ?>" data-value="orders_id#<?php echo htmlentities($vo['orders_id']); ?>" data-csrf="<?php echo systoken('remove'); ?>">删 除</a><?php endif; ?></td><!-- 查看记录 --><td><a data-modal="<?php echo url('index/getRecord'); ?>?order_id=<?php echo htmlentities($vo['orders_id']); ?>">查看记录</a></td></tr><?php endforeach; else: ?><h2>没有待审核订单</h2><?php endif; ?></tbody></table></body></html></div></div></div><script>    $(function() {
      $("#WaitToApprovalOrders").trigger('click')
      // 点击订单分类获取该类订单
      $(".layui-tab-title li").click(function() {
        $.ajax({
          type: "post",
          url: "orders/OrderNavigation/get" + this.id,
          success: function(data) {
            $("#orders").html(data)
          }
        })
      })
    })
</script>